### ISSUE TITLE
Consider adding a function `either`?

### ISSUE THREAD

**Issue by singularitti** [jkrumbiegel/ReadableRegex.jl#2]
Which could make `r"a"` and `r"b"` to be `r"a | b"`?

**Comment by jkrumbiegel** [comment]
There is `one_out_of(targets...)` which works like that, but you can also use `[rs_a, rs_b, ...]` or `(rs_a, rs_b, ...)`

**Comment by jkrumbiegel** [comment]
For example, you can do `rs"c" * ["ool", "ute"]` to match cool or cute

**Comment by singularitti** [comment]
Get it, thank you! Could this be added to README.md? It's not so obvious from the function's name.

**Comment by jkrumbiegel** [comment]
I renamed `one_out_of` to `either` after your suggestion, I think it's a better name and sounds less similar to the count functions
