### ISSUE TITLE
lazy?

### ISSUE THREAD

**Issue by ericphanson** [jkrumbiegel/ReadableRegex.jl#4]
Is it possible to do lazy quantifiers? I ended up just taking the output of ReadableRegex and putting in the `?` by hand, so ReadableRegex was quite helpful, but I figure maybe there could be just a `lazy(...)` function to add it.

E.g.
```julia
julia> find_graphics_with_arg = @compile exactly(1, "\\includegraphics[") * capture(zero_or_more(NON_LINEBREAK)) * exactly(1, "]{") * capture(zero_or_more(NON_LINEBREAK)) * exactly(1, "}")
r"(?:\\includegraphics\[){1}(.*)(?:\]\{){1}(.*)(?:\}){1}"

julia> find_graphics_with_arg = r"(?:\\includegraphics\[){1}(.*?)(?:\]\{){1}(.*?)(?:\}){1}" # add two ?'s by hand
r"(?:\\includegraphics\[){1}(.*?)(?:\]\{){1}(.*?)(?:\}){1}"
```
but maybe it could be
```julia
 find_graphics_with_arg = @compile exactly(1, "\\includegraphics[") * capture(lazy(zero_or_more(NON_LINEBREAK))) * exactly(1, "]{") * capture(lazy(zero_or_more(NON_LINEBREAK))) * exactly(1, "}")
```

**Comment by jkrumbiegel** [comment]
I'll look into it, that seems easy to add! In general I've found that there's a never ending rabbit hole of regex intricacies :)

You can also add "raw" parts into the RegexString with the `rs""` macro. So as a workaround I think `zero_or_more(NON_LINEBREAK) * rs"?"` could also work.

**Comment by ericphanson** [comment]
Ah, that's a good workaround, thanks!

**Comment by jkrumbiegel** [comment]
I just tagged a version that has lazy and possessive quantifier functions, if you want to use those.
