### ISSUE TITLE
question  -  multiple matches between substrings

### ISSUE THREAD

**Issue by Lincoln-Hannah** [jkrumbiegel/ReadableRegex.jl#8]
```
reg = @compile look_for( "[" * one_or_more(ANY) * "]"  )

eachmatch( reg , "[something][something2][something3]" ) 
```

I'd like to get three matches here instead of 1.   Is this possible?

**Comment by jkrumbiegel** [comment]
As ANY also matches the brackets, I think you need to use `lazy_one_or_more` so that the inner part stops matching once the first closing bracket is encountered.

**Comment by jkrumbiegel** [comment]
Also the `look_for` without keyword arguments doesn't do anything :)

**Comment by Lincoln-Hannah** [comment]
Thanks :)

**Comment by Lincoln-Hannah** [comment]
Would it be possible to have a shorthand for lazy_one_or_more(ANY).   Like $X, so you could write

`@compile   "fixed_text_1   $X   fixed_text_2   $X  fixed_text3" `

instead of 

`@compile  "fixed_text_1" * lazy_one_or_more(ANY) * "fixed_text_2"  *  lazy_one_or_more(ANY)  *  "fixed_text_3"`

               `
